### PR TITLE
WIP: (US126259) Adds serge support and fr-ON support

### PR DESCRIPTION
**Pull request by adamsk34**
# Rally

https://rally1.rallydev.com/#/378960033600d/dashboard?detail=%2Fuserstory%2F514985795596&fdp=true?fdp=true

### CODE REVIEW

**Comment by svanherk** [comment]
Hey @adamsk34! Sorry for eavesdropping on your draft PR, but figured I should raise this before you get too far along.  I'm going to be rewriting a number of these components in `core` soon, which doesn't have an `fr-on` file because it's all "basic" terminology that we don't want a client to be able to modify anyways.  Are there certain langterms in here that you're worried will want to be customized?  I'm interested because that could affect:
a) how things get implemented in core (maybe some langterms are instead passed by consumers)
b) whether you need to update all components here, or just the ones with more specialized terms

**Comment by adamsk34** [comment]
> Hey adamsk34! Sorry for eavesdropping on your draft PR, but figured I should raise this before you get too far along. I'm going to be rewriting a number of these components in core soon, which doesn't have an fr-on file because it's all "basic" terminology that we don't want a client to be able to modify anyways. Are there certain langterms in here that you're worried will want to be customized? I'm interested because that could affect:
a) how things get implemented in core (maybe some langterms are instead passed by consumers)
b) whether you need to update all components here, or just the ones with more specialized terms

Hi Stacey! I was under the impression that all language would be modifiable.

From the fr-ON feature https://rally1.rallydev.com/#/12024503567ud/custom/399523971908?detail=%2Fportfolioitem%2Ffeature%2F502780395048&fdp=true&fdp=true?fdp=true
> TELO’s contract requires that they’re able to customize all terminology in the product

But perhaps I am mistaken.

**Comment by svanherk** [comment]
I was under the impression that there were specific terms that translate awkwardly for K12 in French that they were interested in changing (and the contract allows them to).  But I can take that back to the team and inquire - would be good to get a better sense of what they want to do

**Comment by adamsk34** [comment]
Closing this PR because this repo is being exempted from the fr-ON stuff

**Pull request closed without merging**
