### PR TITLE
US134327 - Remove text for portfolio header changes

### PR DESCRIPTION
**Pull request by EvanLemieux**
## Description
Changes proposed are to satisfy a design change in folio. 

image

image

### CODE REVIEW

**Comment by jameswklassen** [comment]
Are the langterms still used for accessibility purposes? If not we can probably remove them? 🤷

**Comment by EvanLemieux** [comment]
> Are the langterms still used for accessibility purposes? If not we can probably remove them? 🤷


> Are the langterms still used for accessibility purposes? If not we can probably remove them? 🤷

They're used in the other component still, so I didn't remove them

**Comment by svanherk** [comment]
Just checking - this is something we want changed everywhere these are used?  Insights dashboards also use these tags.

**Comment by EvanLemieux** [comment]
> Just checking - this is something we want changed everywhere these are used? Insights dashboards also use these tags.

Code search showed only a test using this component, but if they do use it then no. This was a change intended for only folio.

**Comment by svanherk** [comment]
> Code search showed only a test using this component, but if they do use it then no. This was a change intended for only folio.
Edit: Further investigation leads me to believe they have created their own implementation? https://github.com/Brightspace/insights-assessment-quality-dashboard/blob/master/components/applied-filters.js

Oh wow, ok that's good to know... I wasn't aware of that.  Official tag and tag group components (and then filter tags) is coming soon so we'll need to learn what functionality they needed that wasn't available to see if we can incorporate it.

But anyways, looks like you're right and that doesn't affect what you're doing here.  Ignore me!

**Review by jameswklassen — APPROVED** [review]

**Pull request merged**
